# Generated by Django 6.0.3 on 2026-04-02 00:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la escuela')),
                ('cct', models.CharField(blank=True, max_length=15, null=True, verbose_name='Clave CCT')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del periodo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('ciclo_escolar', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del grupo')),
                ('grado', models.SmallIntegerField(choices=[(1, '1° Semestre'), (2, '2° Semestre'), (3, '3° Semestre')])),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Nocturno', 'Nocturno')], max_length=20)),
                ('ciclo_escolar', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ciclo escolar')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='alumnos.escuela')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['escuela', 'grado', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('curp', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CURP')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('Otro', 'Otro')], max_length=10, null=True)),
                ('ingreso_familiar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ingreso familiar mensual (MXN)')),
                ('becado', models.BooleanField(default=False, verbose_name='¿Tiene beca?')),
                ('distancia_escuela_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Distancia a la escuela (km)')),
                ('nivel_estudios_padre', models.CharField(blank=True, choices=[('Sin', 'Sin estudios'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Bachillerato', 'Bachillerato'), ('Superior', 'Superior')], max_length=20, null=True, verbose_name='Nivel de estudios del padre')),
                ('nivel_estudios_madre', models.CharField(blank=True, choices=[('Sin', 'Sin estudios'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Bachillerato', 'Bachillerato'), ('Superior', 'Superior')], max_length=20, null=True, verbose_name='Nivel de estudios de la madre')),
                ('acceso_internet', models.BooleanField(default=True, verbose_name='¿Tiene acceso a internet en casa?')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='alumnos.grupo')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('materia', models.CharField(max_length=100, verbose_name='Materia')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='alumnos.alumno')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='alumnos.periodo')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'unique_together': {('alumno', 'periodo', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_clases', models.PositiveIntegerField(verbose_name='Total de clases en el periodo')),
                ('clases_asistidas', models.PositiveIntegerField(verbose_name='Clases a las que asistió')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='alumnos.alumno')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='alumnos.periodo')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'unique_together': {('alumno', 'periodo')},
            },
        ),
    ]
