# Generated by Django 6.0.3 on 2026-04-02 00:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosCargados',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('tipo', models.CharField(choices=[('calificaciones', 'Calificaciones'), ('asistencias', 'Asistencias'), ('encuesta', 'Encuesta socioeconómica'), ('mixto', 'Datos mixtos')], max_length=30)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Archivo cargado',
                'verbose_name_plural': 'Archivos cargados',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel_riesgo', models.CharField(choices=[('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo')], max_length=10, verbose_name='Nivel de riesgo')),
                ('probabilidad_desercion', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Probabilidad de deserción (0–1)')),
                ('factores_shap', models.JSONField(blank=True, null=True, verbose_name='Valores SHAP por factor')),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de predicción')),
                ('recomendacion_llm', models.TextField(blank=True, null=True, verbose_name='Recomendación generada por LLM')),
                ('modelo_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versión del modelo')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='alumnos.alumno')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='alumnos.periodo')),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
                'ordering': ['-fecha_prediccion'],
                'unique_together': {('alumno', 'periodo')},
            },
        ),
    ]
